### ISSUE TITLE
Default styles

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#263]
Can you implement default styles like in the SADC-GIP?
https://github.com/kartoza/SADC-GIP-Support/issues/4

**Comment by dimasciput** [comment]
Hi @ArnaudIGRAC I have tried to implement this, the importer that we used in sadc is vastly different from IGRAC. This could take a long time to implement, since I need to learn the new importer and basically write a different logic for this. So do you still want me to pursue this? This could take 2-3 days, I'm not really sure. cc @timlinux @meomancer

**Comment by ArnaudIGRAC** [comment]
Hi Dimas, this is an important development for us. The list of styles is long enough and we want to avoid new styles to be automatically created without reason. However I understand that we are running out of time, so I would agree to keep that development for the next phase.
