### ISSUE TITLE
create GGRETA viewers

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#312]
Hi Seabilwe, could you please create 3 map viewers, one for each group of GGRETA layers (Trifino, Stampriet and Pretashkent)? Each viewer should contain the whole set of layers from the corresponding group. The order of the layers is not relevant. There is also no need for subfolders.
Permissions: they should be visible and downloadable only to the members of the corresponding groups.
I will care about the metadata myself.
Thank you

**Comment by seabilwe** [comment]
> Hi @ArnaudIGRAC, please check the GGRETA viewers. The Kalahari one is missing a few layers.
> 
> @meomancer I have just created 3 map viewers on https://ggis.un-igrac.org and one of the viewers (https://ggis.un-igrac.org/maps/1859) is giving me issues, there are supposed to be 65 layers there but after saving the map there are less layers, each time I add the missing layers they are removed.

Hi @meomancer, I am still having this issue

**Comment by ArnaudIGRAC** [comment]
Hi Seabilwe, some layers are also missing in 
Pretashkent: 
- sdc_as47_protected:kaz_aqBound_line
- sdc_public:kaz_lakes

Trifino:
- sdc_public:TRF_hydrogeology_POL

**Comment by seabilwe** [comment]
Thanks @ArnaudIGRAC will check them out and add them

**Comment by seabilwe** [comment]
> Hi Seabilwe, some layers are also missing in
> Pretashkent:
> 
>     * sdc_as47_protected:kaz_aqBound_line
> 
>     * sdc_public:kaz_lakes
> 
> 
> Trifino:
> 
>     * sdc_public:TRF_hydrogeology_POL

They have been restored @ArnaudIGRAC, they were in the viewer, just the style was not rendering. Admire helped restore them

**Comment by ArnaudIGRAC** [comment]
The layers are fine but they don't display as they should in the viewers (see also #369)
![image](https://user-images.githubusercontent.com/64771599/107343711-e5b4dd00-6ac1-11eb-8628-00e09b75d24a.png)

**Comment by seabilwe** [comment]
I'll have  a look at them

**Comment by NyakudyaA** [comment]
This has been quite tricky to debug but here are my findings
## Browsers

* Chrome - works out of the box
* Firefox - Doesn't work
* Safari - didn't test

## Root Cause
In firefox, the request is being generated without an auth token i.e https://ggis.un-igrac.org/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=sdc_as47_protected:kaz_admin_territorial_division&STYLES=&SRS=EPSG:3857&CRS=EPSG:3857&TILED=true&access_token=None&WIDTH=256&HEIGHT=256&BBOX=7827151.696402047,4383204.9499851465,8140237.764258129,4696291.017841228

Instead of having a token.

@ArnaudIGRAC  here is the solution
## Solution

* Clear all browser cookies if the problem exists and the viewers will work. If the problem persists then we can investigate why the auth toke is still being generated as None
* test in private mode for similar issues

**Comment by ArnaudIGRAC** [comment]
Thank you Admire, it works indeed.
