### ISSUE TITLE
licenses modified in ggis.un-igrac.org

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#313]
We had defined licenses in staging version. They have been reset in ggis.un-igrac.org
![image](https://user-images.githubusercontent.com/64771599/104465868-cf942980-55b4-11eb-9134-71ceb2849286.png)

**Comment by ArnaudIGRAC** [comment]
Licenses of layers seem to have been lost again. See for instance https://ggis.un-igrac.org/layers/geonode_data:geonode:TBA_map_2020_02
Please try to fix this asap, this is a problem since layers can already be downloaded by our users.

**Comment by lucernae** [comment]
We will try to figure out a way @ArnaudIGRAC .

For future context, what really happens is like this:

1. I fixed the root cause in #318
2. @meomancer restored the values just like in staging instance
3. It got reset again, because the underlying problem was that GeoNode will reset basic initial data to original configurations (which is the license). Ideal fix would be to deploy the latest changes into production. Hopefully this can be done in the release schedule.
4. In the meantime, I will try to figure out a way to patch this as a hotfix directly into the prod server.

**Comment by meomancer** [comment]
Edited on production  @ArnaudIGRAC @lucernae 
I'm going to put this as our fixture to make restoring fast

**Comment by meomancer** [comment]
this is fixed
and not the fixture already in GGIS too
https://github.com/kartoza/IGRAC-GGIS/blob/develop/django_project/igrac/fixtures/initial_data.json

**Comment by lucernae** [comment]
@meomancer the fixtures needs to be persisted too in the deployment because it's still using the old image

**Comment by ArnaudIGRAC** [comment]
hi Irwan, there are still layers with wrong licenses. See for instance
https://ggis.un-igrac.org/layers/twap_public:twap_public:twap_sids_socioeconomic_totgwabstraction
