### ISSUE TITLE
[EPIC] Security hardening on production

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#317]
We need to harden security in production, example: change password to be more complex.

**Comment by meomancer** [comment]
> SMTP connection for email sending have to use secure TLS server. We need to confirm to @ArnaudIGRAC if IGRAC already have SMTP user credentials that we can use to send emails. Otherwise the emails will be sent from kartoza.com domain email.

we need ro direct this question to stefan

**Comment by meomancer** [comment]
We decide to keep the current one, but not expose database to outside
Is this approach secure @lucernae ?

**Comment by lucernae** [comment]
To some extent, yes.

**Comment by meomancer** [comment]
we keep current security setup for now and revisit it in future
we need to not expose database to outside of server

**Comment by lucernae** [comment]
I need to raise this issue again as I believe the recent attack to GGIS Server is due to it's weak postgres password.
I don't have a proof yet, but so far this problem happens on a server that uses default postgres password for geonode.

If my suspicion is correct, that means the attacker is capable of executing shell scripts from just SQL command, even though the connection to postgres is internal cluster only.

I added pg_hba rule to only accept pod to pod communication only. But we still need to change the password.

I still propose for us to change it via GeoServer REST API and detect what role name is used for all the datastores in GeoServer. Rollout new password for all roles and store the secret somewhere in Nextcloud.

From the DB side, create a new role for each specified database and only grant access to that specified database. I think this should be an ad hoc command. But first we need to identify role --> database association from the REST API list. Then we rollout credential changes by executing PUT command for impacted datastores to change the role + password. Finally, we switch GeoNode's database credentials to use the new role by applying the new k8s manifests.

@NyakudyaA do we have anything else to prepare the impact this will have for day-to-day GIS workflow, for GGIS team?

**Comment by NyakudyaA** [comment]
> I need to raise this issue again as I believe the recent attack to GGIS Server is due to it's weak postgres password.
> I don't have a proof yet, but so far this problem happens on a server that uses default postgres password for geonode.
> 
> If my suspicion is correct, that means the attacker is capable of executing shell scripts from just SQL command, even though the connection to postgres is internal cluster only.

Using the default password is never a good idea. I think your suspicion is correct.

> 
> I added pg_hba rule to only accept pod to pod communication only. But we still need to change the password.
> 
> I still propose for us to change it via GeoServer REST API and detect what role name is used for all the datastores in GeoServer. Rollout new password for all roles and store the secret somewhere in Nextcloud.
> 
> From the DB side, create a new role for each specified database and only grant access to that specified database.

I think this should be an ad hoc command. But first we need to identify role --> database association from the REST API list.


 Then we rollout credential changes by executing PUT command for impacted datastores to change the role + password. Finally, we switch GeoNode's database credentials to use the new role by applying the new k8s manifests.
> 
> @NyakudyaA do we have anything else to prepare the impact this will have for day-to-day GIS workflow, for GGIS team?

Changing credentials will not affect the end users in the system. Just make sure when you create the role in  each database it will have write access to all the tables in the db so that the WFS transaction will work.

**Comment by lucernae** [comment]
I have rolled out the new credentials changes.
I give write access to all the tables in the db/schema, hopefully the WFS transaction will work.
@NyakudyaA can you please check the WFS transaction?
After that, we can close the ticket.

**Comment by NyakudyaA** [comment]
> I have rolled out the new credentials changes.
> 
> I give write access to all the tables in the db/schema, hopefully the WFS transaction will work.
> 
> @NyakudyaA can you please check the WFS transaction?
> 
> After that, we can close the ticket.

@seabilwe can you check this. Basically all you need to do is select a layer in geonode and edit the data, make sure the changes are being saved.

**Comment by NyakudyaA** [comment]
@lucernae I have tested this with a single layer and it works, we can close the ticket
