### ISSUE TITLE
Management of styles in GeoNode

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/IGRAC-GGIS#326]
There are a lot of duplicates in the way the GeoNode is handling the styles.

# Uploading Layers

* Navigate to GeoNode 
* Upload a layer without a style
* Check-in  Geoserver - a new style has been created.
* The new style is not associated with any workspace - Also the style gets a new name ie `geonode_index`

**NB** This behavior is wrong because a layer should inherit default styles based on the geometry i.e
* Point - point.sld
* Polygon - polygon.sld
* Line - line.sld
*Raster - raster.sld

# Duplicated layers without Workspaces

We seem to have a lot of layer styles that are not assigned to any workspace. Ideally, these should be removed.
Currently, they are about 1700 styles
![lyers](https://user-images.githubusercontent.com/2510900/105194265-11d3e280-5b42-11eb-8b78-2d4e6be9f172.png)

* We need to move the styles that do not have a workspace to a proper workspace and delete them as needed.

Using the GeoServer Rest API I can see that they are 780 styles that are linked to the layers meaning the styles should be deleted which have no relationship to any layer

**Comment by NyakudyaA** [comment]
I have cleaned up these styles in staging but will keep the ticket open for a referral to implementation of the default styles

**Comment by meomancer** [comment]
The default styles is taking time to be implemented to current geonode
as per : https://github.com/kartoza/IGRAC-GGIS/issues/263#issuecomment-779533487

maybe we can close this ticket for now @NyakudyaA

**Comment by NyakudyaA** [comment]
@meomancer You should keep this ticket open because the default GeoNode behaviour works out of the box

**Comment by meomancer** [comment]
we can remove this for current project version for now

**Comment by ArnaudIGRAC** [comment]
I noticed that there are still style duplicates. When you upload a layer, a new style is created twice (once in GeoNode workspace, once in a blank workspace).

**Comment by ArnaudIGRAC** [comment]
I assume this is the reason why style of this layer doesn't match the legend
![image](https://user-images.githubusercontent.com/64771599/109499814-aa407980-7a95-11eb-9112-5d92b62bd2e0.png)
In Geoserver
![image](https://user-images.githubusercontent.com/64771599/109499854-b4fb0e80-7a95-11eb-8e8b-e9d18866b26f.png)

**Comment by ArnaudIGRAC** [comment]
Please solve this issue, otherwise the styles will be impossible to manage

**Comment by ArnaudIGRAC** [comment]
This issue is still pending, cfr #500

**Comment by meomancer** [comment]
hi @ArnaudIGRAC @NyakudyaA 
I checked it and also tried it on production
The style does note create duplication anymore (with geonode 4)

When i upload a layer
![Selection_001](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/9d424671-a71b-430c-ba53-3cc9c151d677)

But it still creates duplication on geonode itself
![Selection_002](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/58b44dea-13c4-4fb9-8b65-30c3f7f9c3bf)

But the style and the legend is ok, because i checked it, the style that geonode using to the layer is the correct one from geoserver
![Selection_004](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/db4d54b6-0c61-45a4-b0b7-466475a312d2)

I also tried to upgrade the geoserver, they still creates duplications just on geonode, not on geoserver
I think we can ignore the duplications on geonode, i also created script to clean style
https://github.com/kartoza/IGRAC-GGIS/commit/e06463c768e1f8b84225efbe3175877a390d9f69#diff-12bb5f76412f37bf90b505152bab81a2cb71f81d04eb75cdef2f2913d2c99f8eR7

It will check styles that does not have any relationship on geonode (but not on geoserver)
And it will delete the style on geonode and geoserver, i think it is quite destructive (maybe we can create backup before run it)
Or maybe we can ask Admire to clean it on production?
https://github.com/kartoza/IGRAC-GGIS/issues/326#issuecomment-771556269

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, style duplicates are quite an issue in GeoNode, it really makes the management of styles more complicated. Isn't there a solution to this problem? Or does the problem arise only whenever a new layer is uploaded and a default style is created? in which case assigning default styles will solve the problem.

Have you created default styles? like you did with the SADC-GIP https://github.com/kartoza/SADC-GIP-Support/issues/4

I don't have a strong opinion about the best way to clean the list of styles, however please do a backup before running your script.

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, here are some datasets to test [Dataset_training.zip](https://github.com/kartoza/IGRAC-GGIS/files/11614843/Dataset_training.zip)

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
it will be fixed from : https://github.com/kartoza/geonode/commit/6985ae4e0f8a74afea78982b3042592f49cbfa92
There is no style created on geoserver when we create layer without sld file

I will deploy it to staging, so we can test it

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
I have deployed the fix on staging
Could you try it?

When we don't upload sld, it would use point, polygon, line or raster style

**Comment by ArnaudIGRAC** [comment]
It doesn't work properly Irwan. When you upload a layer it will first receive a new style. Then it seems that the layer reuploads with the default style.

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
what layer did you upload? is the new style deleted?

the geonode is working like that, by default it creates new style automatically (through geoserver) using name geonode_xxxx
and they delete that geonode_ style and recreate style without geonode_

i update it by reapply the default style on it

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, I uploaded a random polygon shapefile, and it went as you described. I am not sure I like this process, let's discuss about it during our meeting next week. Also, I noticed that the Manage style has disappeared from Geonode.

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, As discussed last week, there is no real need to assign default styles as long as each layer has a unique style. The issue was with the style manager, but this functionality has been removed. Have you figured out how to handle layers with multiple styles in GeoNode 4? See for instance this layer https://ggis.un-igrac.org/catalogue/#/dataset/1810 who has 5 associated styles as you can see in https://ggis.un-igrac.org/view/marportal/. How can I manage that?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
I can't figure it out, i have asked @NyakudyaA to check this

**Comment by NyakudyaA** [comment]
Opened an upstream issue https://github.com/GeoNode/geonode/issues/11272

**Comment by NyakudyaA** [comment]
This has been moved to the map settings. So it's only possible to use the layer with an alternate style in the context of creating a new layer
![Peek 2023-07-17 11-27](https://github.com/kartoza/IGRAC-GGIS/assets/2510900/c918ea11-7d71-430c-8adb-50e98b41af97)

**Comment by ArnaudIGRAC** [comment]
Thank you
