### ISSUE TITLE
Geoserver login

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#331]
Hi @lucernae @meomancer I am having issues with staying logged in on the Geoserver production site. I keep getting logged out each time I update a style and you find that the update was no saved.

I have sent you the screen casts, there is an error when uploading them here

**Comment by lucernae** [comment]
Hi @seabilwe I did some investigation and here’s what I found.

There is an upstream issue with the community module OAuth2 that affects Styles > Layer Preview page.
In summary, GeoServer OAuth2 module will try to inject `access_token` into the URL of the page. But it doesn’t do so cleanly in layers preview. The resulting WMS url becomes `https://ggis.un-igrac.org/geoserver/?access_token=<token>/<layer name/wms`. It was supposed to be without the access_token (because session is active in the page). Fixing this needs to be done in GeoServer, but I found out from this JIRA ticket that it was fixed from GeoServer 2.19 onwards:
https://osgeo-org.atlassian.net/browse/GEOS-9836

In conclusion, I can only advise us to do this:

1. When we do GeoServer management, login directly as GeoServer admin user (I will give you the credentials). So we prevent the OAuth module from tampering the URL.
2. I found out that surprisingly staging server GeoServer version works (or half working) when you log in via OAuth. If you click the Styles > Layer Preview once, it will have the same error. But at the second time, it will work because the authentication resets and login happens in the background, so the layers preview are visible. I updated production server to use this exact same GeoServer image in the staging.

I did the best I can to use the same exact docker image with the staging (for user that needs to login via OAuth). However if you can assume the role of GeoServer superadmin, I advise to do approach 1, as it is less disruptive. I don’t think we can just upgrade directly to GeoServer 2.19 without further testing. 

CC @meomancer FYI

**Comment by NyakudyaA** [comment]
great diagnosis @lucernae. From my experience upgrading, GeoServer should not really affect the Geonode. But obviously, this needs to be tested because of the extensions that are installed within the image

**Comment by seabilwe** [comment]
thanks so  much @lucernae, I will stick with the first option when logging into GeoServer

**Comment by meomancer** [comment]
is this issue still happening? maybe we can close this ticket

**Comment by NyakudyaA** [comment]
@meomancer i haven't experienced this in a while so you can close
