### ISSUE TITLE
igrac.org data points?

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#332]
What are the igrac.org data points? Are they dummy data? If yes, can we delete them?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC @clau1313 
Every wells that was dummy data now are clear 
Could you check it?

**Comment by ArnaudIGRAC** [comment]
igrac.org data are gone, thanks! I see several data records without GGIS UID, how is that possible? @clau1313 can you also have a look?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC most of data does not have organisation
i think it is because of it doesn't have organisation from ggmn
example:
https://ggis.un-igrac.org/groundwater/record/2427/edit
it does not have organisation so we can't create GGIS UID

or should we still generate GGIS UID, although it does not have organisation?

**Comment by clau1313** [comment]
Hi, this is very strange, since all data from the GGMN was tied to an organisation (it was a requirement to upload data in the system). It seems that this information was lost when retrieving data from the GGMN API.

@meomancer could you fill in the name of the organisation based on the country? (I can tell you which country matches which organisation).

**Comment by dimasciput** [comment]
@clau1313 I'm almost certain that many wells doesn't have an organization attached to them. But let me check it again tomorrow.

**Comment by meomancer** [comment]
I'm going to close this issue because the issue that we disscuss in further is already different with this tickets

the ticket
#358
