### ISSUE TITLE
embedding content in Wagtail

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#362]
Hi Dimas, is it possible to embed content from another webpage in Wagtail? The reason why I am asking is that our user manual will refer much to the GeoNode user guide (https://docs.geonode.org/en/master/usage/index.html). It would be user friendlier to insert that content among the main text instead of providing hyperlinks to that page.

**Comment by ArnaudIGRAC** [comment]
Something like this is not pleasant to read
![image](https://user-images.githubusercontent.com/64771599/106770443-44033b00-663e-11eb-8601-f9545ec280b0.png)

**Comment by dimasciput** [comment]
Hi @ArnaudIGRAC , unfortunately I don't think this is possible.

**Comment by dimasciput** [comment]
@ArnaudIGRAC basically we need to update something in the wagtail, and also it won't look good because the geonode doc page has a sidebar, we can't remove the sidebar since it's not our website 
![image](https://user-images.githubusercontent.com/1979569/106832700-bc144400-66c4-11eb-866f-3cc8ffef30c4.png)
cc @meomancer

**Comment by ArnaudIGRAC** [comment]
Thank you Dimas

**Comment by ArnaudIGRAC** [comment]
There seems to be a way though: https://docs.readthedocs.io/en/stable/guides/embedding-content.html#calling-the-embed-api-directly

**Comment by dimasciput** [comment]
Ah okay, that should solve the sidebar issue, but it still not possible in the current wagtail, we'll try to update the wagtail so it can support the embed. cc @meomancer

**Comment by dimasciput** [comment]
@ArnaudIGRAC this will take 2 hours to half a day

**Comment by dimasciput** [comment]
Hi @ArnaudIGRAC , I tried to embed the docs file and it doesn't look good 

Here's the embedded page : 
![image](https://user-images.githubusercontent.com/1979569/107174644-580fb980-69fd-11eb-920b-8d529571574c.png)

Here's the actual page :
![image](https://user-images.githubusercontent.com/1979569/107174718-7ecdf000-69fd-11eb-98c2-aa8daba8c7cf.png)

This is because we didn't get the CSS file (CSS describes how HTML elements are to be displayed on screen), and also we couldn't get the correct path of the images so some of them are missing.

So what do you think? Should we still implement this or not?

**Comment by dimasciput** [comment]
cc @meomancer

**Comment by ArnaudIGRAC** [comment]
Thank you Dimas, let's discuss  tomorrow during our meeting

**Comment by timlinux** [comment]
As discussed, should be fine to copy and paste text from the geonode as they are CC-SA

© Copyright 2017-2020, Open Source Geospatial Foundation, CC-SA Revision 68e026c9.

Just make sure to include the above acknowledgement in each copied over page.

**Comment by meomancer** [comment]
let's close this
