### ISSUE TITLE
style disappears

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#381]
I tried to assign the style GWB to the layer https://ggis.un-igrac.org/layers/geonode_data:geonode:spain. It didn't work. WHen I tried again, I realized that this style is not available anymore. Other layers using this style mention : "No styles associated with this layer", although it is still visible. See for example https://ggis.un-igrac.org/layers/tbamap2015:tbamap2015:gwb_2019_austria

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
i'm not sure why we can't assign GWB to spain from geonode, i already analyzed it but can't check why spain can use GWB from geonode

But i already add it from geoserver directly, so basically the style already assigned
![Selection_104](https://user-images.githubusercontent.com/4530905/108014852-6c793500-7041-11eb-94cd-395798868554.png)

**Comment by ArnaudIGRAC** [comment]
Under "manage" styles, I put "GWB" as default and removed "spain". Then I noticed that "GWB" has been removed again and only "spain" is left. This is not normal behaviour, can you please investigate?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
i already fixed it

yes, it is hard to analyze because this is on the server and just happens on spain layer
I can't find any error for any logs
and it will takes time for me to analyze it

i checked on other layer, they are working fine for manage style
could you recheck it? i already clean that laye

and if this happens again, we could come back to this issue

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan, let's hope it is just an isolated bug
