### ISSUE TITLE
GGIS unavailable!

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#401]
![image](https://user-images.githubusercontent.com/64771599/111593617-6a360200-87ca-11eb-8f28-e76fdf8af055.png)

**Comment by meomancer** [comment]
this is coming from rancher2 that container for ggis and also sadc staging is down
could you check this @lucernae ? I'm not familiar with rancher2 for this case

**Comment by lucernae** [comment]
I'm on it. @ArnaudIGRAC @meomancer .
There seems to be some issue in the Hetzner side.

**Comment by lucernae** [comment]
We've fixed it gradually. Frontend website got back up once I responded @meomancer 's ping.
Background services seems to be recovering gradually until I have to intervene myself.
All service running green now.

I checked a layer like this: https://ggis.un-igrac.org/layers/?limit=5&offset=0&title__icontains=EXP_C45_2021_fs20_Sk_blank_rc&abstract__icontains=EXP_C45_2021_fs20_Sk_blank_rc&purpose__icontains=EXP_C45_2021_fs20_Sk_blank_rc&f_method=or

shows "Layer is not ready".
It was uploaded on 16th March, so I'm not sure if this is because of the crash.
I think reuploading will fix that warning.

**Comment by meomancer** [comment]
this is fixed
