### ISSUE TITLE
Deployment default

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#408]
hi @lucernae 

could you help me setup deployment using correct configuration by default (example when the server was down before, the configuration turns to be incorrect)

1. On uwsgi.conf
    harakiri = 2400
   
2. local_settings.py
    DATABASE_URL = 'postgis://{}:{}@{}:{}/{}'.format(GEONODE_DATABASE_USER, GEONODE_DATABASE_PASSWORD, GEONODE_DATABASE_HOST, GEONODE_DATABASE_PORT, GEONODE_DATABASE)

**Comment by lucernae** [comment]
We already put these configuration in place. If it gets deployed from kartoza/devops it will be applied.

More details:

Both of them are declared in separate configuration override files (So that it won't be accidentally rewritten by devs in Rancher):
https://github.com/kartoza/devops/blob/7da97371441b32d9ed852412da0b5eca7f02f19a/rancher-2.x/manifests/projects/ggis/geonode-ggis-override-config-configmap.yaml

uwsgi.conf are mounted as /uwsgi.conf
local_settings.py are mounted as /spcgeonode/geonode/override_settings.py
This rule are declared here:
(https://github.com/kartoza/devops/blob/7da97371441b32d9ed852412da0b5eca7f02f19a/rancher-2.x/manifests/projects/ggis/values.yaml#L103)

DJANGO_SETTINGS_MODULE is set to `geonode.override_settings`.
This rule are declared here:
(https://github.com/kartoza/devops/blob/7da97371441b32d9ed852412da0b5eca7f02f19a/rancher-2.x/manifests/projects/ggis/patches/geonode-ggis-deployment.yaml#L13)

uwsgi started using /uwsgi.conf
This rule are declared here:
(https://github.com/kartoza/devops/blob/7da97371441b32d9ed852412da0b5eca7f02f19a/rancher-2.x/manifests/projects/ggis/values.yaml#L22-L25)

**Comment by meomancer** [comment]
we can close it for now until the error raise again
i'm sorry i don't remember which file that was wrong
