### ISSUE TITLE
List of maps using this layer (bug)

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#415]
The map where this layer is used appears several times
https://ggis.un-igrac.org/layers/geonode_data:geonode:Global_MAR_Inventory
![image](https://user-images.githubusercontent.com/64771599/114368199-77ea6780-9b7d-11eb-9bd7-211b23677e0e.png)

**Comment by meomancer** [comment]
Here is the analysis:

1. **Not BUG** : That layer are being used by multiple maps but they are have same name
Which are:
https://ggis.un-igrac.org/maps/1233
https://ggis.un-igrac.org/maps/2146
https://ggis.un-igrac.org/maps/2148
https://ggis.un-igrac.org/maps/2147
https://ggis.un-igrac.org/maps/2145

Please fix these by rename the map or remove it if there is duplication

2. **BUG** : One map has multiple Global MAR
Example:
https://ggis.un-igrac.org/maps/1233/edit
![Selection_014](https://user-images.githubusercontent.com/4530905/114500894-28766b00-9c53-11eb-89e3-3e6d9520e998.png)
Basically the layer are used multiple time with different styles
This is fixed with : https://github.com/kartoza/geonode/tree/3.2.2
Will be released on version 1.1.7

Currently i deployed it to staging:
https://staging.igrac.kartoza.com/layers/geonode_data:geonode:Global_MAR_Inventory
basically this layer is used by 2 Map, and 1 map reuse it multiple time

Before:
![Selection_012](https://user-images.githubusercontent.com/4530905/114501084-7f7c4000-9c53-11eb-8467-a09b0deeb688.png)

After:
![Selection_013](https://user-images.githubusercontent.com/4530905/114501107-86a34e00-9c53-11eb-8165-51a8029793b0.png)

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan. The map was indeed duplicated 4 times by one user. I just deleted those duplicates.
![image](https://user-images.githubusercontent.com/64771599/114510235-b7c15580-9c36-11eb-90bc-7ccf6a8aa3d1.png)
Strange thing: a few days ago my colleague Stefan also inadvertently duplicated this map. Is there a bug somewhere? Or do these user _save the map as..._? Let's keep an eye on it.
