### ISSUE TITLE
well and monitoring data in external GeoNode platforms

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#416]
Dear colleagues,

The layer https://ggis.un-igrac.org/layers/groundwater:groundwater:Groundwater_Well can be accessed in other GeoNode platforms via remote services, like in the SADC-GIP or the ORASECOM platform. See for example 
https://sadc-gip.org/maps/new?layer=httpsggisun-igracorggeoserverows:groundwater:Groundwater_Well&view=True
However, when you click on a data point in these platforms, the feature box is only made of text (no charts, no hyperlinks). 
![image](https://user-images.githubusercontent.com/64771599/114391194-79288e00-9b97-11eb-9fc4-a069bbadc72c.png)
I guess the GGIS has been customized to support that. What would it take in terms of development to have the same feature boxes in these platforms, as in the GGIS?

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC I think the reason why that happens is that in the SADC the layer is a remote WMS and you cannot define how the metadata is defined in this context because WMS cannot expose column for the layer. 
i.e https://sadc-gip.org/layers/httpsggisun-igracorggeoserverows:groundwater:Groundwater_Well/metadata
![widgets](https://user-images.githubusercontent.com/2510900/114395359-8c8a2800-9b9c-11eb-9330-0f8995bde621.png)

This will need to be an upstream enhancement

**Comment by ArnaudIGRAC** [comment]
Thank you Admire! By upstream enhancement do you mean something to be developed in those external platforms or in the GGIS?

**Comment by NyakudyaA** [comment]
> Thank you Admire! By upstream enhancement do you mean something to be developed in those external platforms or in the GGIS?

If we are to make the change it has to be done in the main GeoNode code and we can then pull the changes to the various instances we have.

Currently, the way it works can be summarised like

* In GeoNode add remote Service
* Geonode determines what type of service it is WMS/ ArcGIS or another GeoNode.
* It then exposes some limited functionality for that layer because it is an external service. ie Updating metadata is possible because it is now saved locally, layer styles cannot be changed etc.
* The identify features use a WMS standard (GetfeatureInfo request) which gets it from an external GeoNode as WMS.
* Because WMS doesn't expose columns we cannot configure the Getfeatureinfo for external services - if development is to take place this is where the magic should happen here.

**Comment by ArnaudIGRAC** [comment]
Would you be able to estimate the size of this development? and would it have consequences for the stability and management of our current GeoNode platforms?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
as per @NyakudyaA comment

this is limitation for using remote data
and also the graph is calling API on GGIS, that it will never work because it is in different domain

The development will taking a lot of time and this is already geonode development (not SADC anymore)

**Comment by ArnaudIGRAC** [comment]
Thank you for your feedback. Wouldn't it be easier if we set up the WFS between the Geoserver of the GGIS and the Geoserver of the SADC-GIP, without going through GeoNode? No need for development then. 
Then the only issue left is for the graphs. But I suppose an url can be fixed. It is a matter of appending "https://ggis.un-igrac/..."
I am asking because of a project coming on with partner organisations. Please let me know your thoughts.

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC You can import the well monitoring data as WFS within the SADC as https://ggis.un-igrac.org/geoserver/groundwater/ows?service=WFS&typeName=groundwater:Groundwater_Well

The only difference with this is that you would be able to configure the getfeatureinfo request to show up properly. 
![capabilit](https://user-images.githubusercontent.com/2510900/114584058-8cfcee80-9c82-11eb-9879-89532d477d11.png)

Another thing is that the layer is expected to be visible to anyone within the Geoserver from igrac

**Comment by ArnaudIGRAC** [comment]
Thank you Admire, I can see the layer in the SADC-GIP now 
https://sadc-gip.org/layers/httpsggisun-igracorggeoservergroundwaterowsservicewfstypenamegroundwatergroundwater_well:Groundwater_Well
But I can't open any attribute box, it doesn't seem to be working. Note that I also had issues when importing the layer as WFS in QGIS. Any idea why?

**Comment by ArnaudIGRAC** [comment]
Dear colleagues, can you please follow up on this? We will be engaging with partner organisations very soon so it is important for us to know what we can offer.

**Comment by meomancer** [comment]
hi @NyakudyaA 
could you help me check this?

**Comment by NyakudyaA** [comment]
@meomancer Yes, the wfs standard does not support getfeature info requests. I completely forgot about that when I suggested the import using wfs.

So what I suggest is that you revert back to using the remote WMS service. Then after importing the layer you edit the metadata for the layer. Instead of using the default getfeatureinfo template you then use a custom getfeatureinfo template
![Screenshot 2021-04-26 at 09 14 52](https://user-images.githubusercontent.com/2510900/116043481-ffe96a80-a66f-11eb-9cf5-ba3993eb0c2d.png)

You could actually do this globally in GeoServer or per workspace,per layer, etc

https://docs.geoserver.org/latest/en/user/tutorials/GetFeatureInfo/index.html

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
can you check this layer?
https://sadc-gip.org/layers/httpsggisun-igracorggeoserverwms:groundwater:Groundwater_Well

I created it using WMS and also the template is same with ggis

NOTE:
- we can't show the graph because it is in different domain, graph is using iframe

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan, this is great, really! 
Regarding the graph, there is a possibility to include iframe in TINY, so I believe you could call the graph from the GGIS. Could we discuss that next week before you go on leave?

**Comment by meomancer** [comment]
hi @lucernae 
could we whitelist the sadc to the GGIS using CORS_ORIGIN_WHITELIST?
so the iframe can be rendered?

For now i added the graph iframe so we can test it while change the setting on ggis
![Selection_130](https://user-images.githubusercontent.com/4530905/116522949-ea8a6f80-a8ff-11eb-9d82-80c0058f81b5.png)

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
This is fixed
Now the chart shows nicely on sadc
please check it
https://sadc-gip.org/layers/httpsggisun-igracorggeoserverwms:groundwater:Groundwater_Well

The fix already deployed to production with 1.1.8

**Comment by ArnaudIGRAC** [comment]
This is great Irwan, a big added value for our partners. Thank you very much!

**Comment by ArnaudIGRAC** [comment]
The attribute tables are not visible anymore, can you please restore it?
https://sadc-gip.org/layers/httpsggisun-igracorggeoservergroundwaterowsservicewfstypenamegroundwatergroundwater_well:Groundwater_Well

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Here is the correct service:
https://sadc-gip.org/services/408/
The layer:
https://sadc-gip.org/layers/httpsggisun-igracorggeoserverwms:groundwater:Groundwater_Well

----------------------------------------------------
This is the not working one:
https://sadc-gip.org/services/406/
The Layer:
https://sadc-gip.org/layers/httpsggisun-igracorggeoservergroundwaterowsservicewfstypenamegroundwatergroundwater_well:Groundwater_Well

And 
https://sadc-gip.org/services/397/
The Layer:
https://sadc-gip.org/layers/httpsggisun-igracorggeoserverows:groundwater:Groundwater_Well

I think we can delete the not working one
