### ISSUE TITLE
can't replace layer

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#423]
I try to replace https://ggis.un-igrac.org/layers/geonode:transboundary_aquifers_basicinformation with the layer hereby attached. I get the following error message. 
![image](https://user-images.githubusercontent.com/64771599/115534562-32721c80-a298-11eb-85bd-47dfd629faaf.png)

Can you please tell me what is going wrong?
[transboundary_aquifers_basicinformation.zip](https://github.com/kartoza/IGRAC-GGIS/files/6349871/transboundary_aquifers_basicinformation.zip)

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
it seems there are 2 layers for that shapefile
https://ggis.un-igrac.org/layers/geonode:transboundary_aquifers_basicinformation
https://ggis.un-igrac.org/layers/twap.gwshare:transboundary_aquifers_basicinformation

could you check they are same or different?
if different, we can rename the new one to other title, because the name are same "transboundary_aquifers_basicinformation"

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, I didn't think the name would be an issue since the two layers are in different stores. Can you please address #424 so I can modify the layer's name?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
this is from the code on the geonode
when replace, it just check the name of the layer (not with store)
so it will check the layer that has name "transboundary_aquifers_basicinformation"
and on current ggis, we have 2 layer has that name "transboundary_aquifers_basicinformation"

>  Can you please address #424 so I can modify the layer's name?

yes, this is the solution, we need to modify the layer name (and also pull it on geonode)

or maybe we can delete the layer 
https://ggis.un-igrac.org/layers/geonode:transboundary_aquifers_basicinformation
and reupoload it, but rename the shapefile (because the layer name is based on the shapefile name)

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan
