### ISSUE TITLE
[GGMN] Replace some data from Sweden

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#466]
Hi @meomancer! A colleague from the SGU realised that in some wells there are some artificial leaps/step trends. So from example, from one day to another there is a change of 2 m in the groundwater table.

I looked into it and found out that this happens at the "connection" between data from the old GGMN and data retrieved from SGU. And this happens because from their side they corrected their data retrospectively, which means that the data we had in the old GGMN was outdated. 

So the solution would be to retrieve all groundwater levels automatically from their system, and forget the data we had in the GGMN, even if our time series were longer (because these data would be erroneous anyway). Would it be possible for you to do that?

If so, they ask me to wait some days to replace the data, so to wait until the end of this week.

Please let me know. Thanks!

**Comment by dimasciput** [comment]
Hi @clau1313, Irwan is still on leave this week and will be back next week.

**Comment by clau1313** [comment]
hi @dimasciput, thanks for letting me know!

**Comment by meomancer** [comment]
hi @clau1313 i'm sorry i was on leave

yes, we can do replace current data with new data from SGU
please let me know when the data is ready so we can run the harvester to drop our data and replace with new data from SGU

**Comment by clau1313** [comment]
hi @meomancer, the data is ready to be replaced. Or did you do it already?

**Comment by meomancer** [comment]
hi @clau1313 
I haven't done anything
Because you said that on the original post

> If so, they ask me to wait some days to replace the data, so to wait until the end of this week.
i though i need to wait some days until the are ready to be replaced

Should i replace now? Is the data ready on SGU to be replaced on our side?

**Comment by clau1313** [comment]
hi @meomancer, no problem. Thanks! Tomorrow is fine.

**Comment by meomancer** [comment]
hi @clau1313 
Every sweden data has been replaced
Could you check it?

**Comment by clau1313** [comment]
hi @meomancer, thanks, the data looks good to me. 

I have an additional question about the graphs. For example, the graph for this well (https://ggis.un-igrac.org/groundwater/record/3186/) looks like this:

![image](https://user-images.githubusercontent.com/36033176/148046311-3de77d6a-6bc5-44cd-aa14-dece287c359f.png)

Both intervals (marked with red and green markers) are the same lenght, but actually the red one covers 6 years and the green one 2 years. 

Another example is the next well (https://ggis.un-igrac.org/groundwater/record/343/):

![image](https://user-images.githubusercontent.com/36033176/148046710-6a8f2689-05be-402e-9c5a-b55991820b9a.png)

The red interval is 10 years, while the green one is only 2 years but it is a lot longer.

So my question is: is it possible to keep the distance between years in the x-azis always the same? (for the sake of consistency).

Thanks!

**Comment by meomancer** [comment]
hi @clau1313 
thank you for the report
yes, it is quite not good

i'm not sure it is possible to fix it from library or not now
i will ask time to finding out how to fix it @clau1313

**Comment by clau1313** [comment]
ok, thanks @meomancer!

**Comment by meomancer** [comment]
hi @clau1313 
the problem is the density of data on the left is lesser than the right one 
so the library creating the chart like that

But we can fix by grouping data depend on zoom (it is already provided by the chart)
Because of it, the data will be less complex than the original
But the detail one still be checked if we zoom in
We also can still the detailed one in the second chart (bottom)

Example:

Before
![Selection_003](https://user-images.githubusercontent.com/4530905/148720947-74c61179-b740-4921-b5a1-f5ba14f0edf3.png)

After
![Selection_004](https://user-images.githubusercontent.com/4530905/148720966-ead91cfc-f3b5-4f5d-a32b-d2b821bf9212.png)

When we zoom in
![Selection_008](https://user-images.githubusercontent.com/4530905/148720977-6a697734-b697-4971-9384-0ce3d1ca6719.png)

Another one
Before
![Selection_001](https://user-images.githubusercontent.com/4530905/148721005-32e528cb-79d6-4950-943b-ebe1aa04c696.png)

After
![Selection_002](https://user-images.githubusercontent.com/4530905/148721013-68af7b84-00e3-4dab-be3d-a78f36039225.png)

Before
![Selection_005](https://user-images.githubusercontent.com/4530905/148721026-85072695-ae6d-4814-9c4a-378678dde7c9.png)

After
![Selection_006](https://user-images.githubusercontent.com/4530905/148721033-fc954bbf-c9dc-4037-8559-f6566609742c.png)


I haven't deployed it @clau1313 
What do you think?

**Comment by clau1313** [comment]
Hi @meomancer, thanks for all the examples. I think it is a good solution. How long does it take to deploy it?

**Comment by meomancer** [comment]
This has been deployed
Could you check it @clau1313 ?

**Comment by clau1313** [comment]
Hi @meomancer, it looks good to me! Thanks. 

I guess that we can close this issue now.
