### ISSUE TITLE
Well and Monitoring data very slow to display on the map

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#477]
It takes ages for the layer to display properly after zooming in/out. Playing with the attribute table is a bit faster but also not great. Any suggestion to improve the performace of these layers in the near future?

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, thank you for the suggestion. Indeed, it is not necessary to synchronize the map with the database all the time if there is no edit in the database. Can you please proceed with the suggested change?

**Comment by ArnaudIGRAC** [comment]
It is still very low to display, we need another fix

**Comment by timlinux** [comment]
@meomancer simple solution for this is to just upgrade the server to something with more CPU power....

**Comment by timlinux** [comment]
I took a look - we are already on a CX51

![imagem](https://user-images.githubusercontent.com/178003/163996333-ed19bcce-7916-4889-8f56-669753e93df5.png)

With 8 cpus' I wonder if  upgrading will help. @NyakudyaA can you please investigate the cause of the bottleneck. Maybe we can cache the wells layer nightly (with the side effect that new well uploads will take up to 24 hours to appear on the platform.

**Comment by NyakudyaA** [comment]
@meomancer Can you point me to the layer in the DB? Are all the fields properly indexed and is the database also properly optimised to maximise the server resources. For now, I think we can investigate the following actions
* Optimise the layer itself. Even materialized views can have indexes because they are tables.
* Are you using row-level triggers ?
* For the updates happening in the main layer is it just random updates or they are specific for an area. If we can get the bounding box for the new data we can use this to seed/truncate the layer using geowebcache.
* We can either use a native cron on the hosts or crontab in the DB to seed layers in GeoServer or refresh the materialized view as a specific time interval if we do not want to use row-level triggers

**Comment by meomancer** [comment]
hi @NyakudyaA @timlinux 
I already created the mv for the layers, but the problem is everytime i save it, it will revert back to old one.

**Well layer**
The layer:
https://ggis.un-igrac.org/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.resource.ResourceConfigurationPage?50&name=Groundwater_Well&wsName=groundwater

The sql should be:
`select id, ggis_uid, original_id, name, feature_type,purpose, status,organisation, country, year_of_drilling, aquifer_name, aquifer_type,manager, detail, location, created_at, created_by, last_edited_at, last_edited_by, public from mv_well_with_uuid where uuid::text like '%uuid%';`

**GGMN**
The layer:
https://ggis.un-igrac.org/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.resource.ResourceConfigurationPage?53&name=Groundwater_Well_GGMN&wsName=groundwater

The sql should be:
`select id, ggis_uid, original_id, name, feature_type,purpose, status,organisation, country, year_of_drilling, aquifer_name, aquifer_type,manager, detail, location, created_at, created_by, last_edited_at, last_edited_by, public from mv_well_ggmn;
`

**Comment by dimasciput** [comment]
@meomancer you need to save in the edit layer page too, not just in the sql view page. I managed to update the ggmn one, but the mv view for well layer has no uuid column.

**Comment by meomancer** [comment]
i see, thank you @dimasciput 
i just saved the sql without save the layer
now it is saved and faster

**Comment by meomancer** [comment]
hi @ArnaudIGRAC @timlinux @NyakudyaA 
Could you try if it is faster or not?
https://ggis.un-igrac.org/view/ggmn
https://ggis.un-igrac.org/view/well-and-monitoring-data

**Comment by ArnaudIGRAC** [comment]
- https://ggis.un-igrac.org/view/ggmn It seems faster indeed
- https://ggis.un-igrac.org/view/well-and-monitoring-data I don't see any data point

**Comment by meomancer** [comment]
Fixed @ArnaudIGRAC 
Could you retry?

**Comment by ArnaudIGRAC** [comment]
Excellent! thank you
