### ISSUE TITLE
Add measurement charts for all data

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#522]
I also now see the graphs for the groundwater quality in New Zealand in the Well and monitoring data record page. But I wonder if it is possible to show which groundwater quality parameters are available per station, in the drop-down menu in the main page (same for groundwater quality data and abstraction from Norway). Otherwise it just looks like there is no data in that monitoring point, because it says “no data found”.

![image003](https://user-images.githubusercontent.com/4530905/214201862-2cd5658b-7530-4efa-a9b4-87fec8d359af.png)

**Comment by meomancer** [comment]
Hi @clau1313 
This has been updated on staging : https://staging.igrac.kartoza.com/view/well-and-monitoring-data/

**Comment by clau1313** [comment]
Thanks @meomancer 

@ArnaudIGRAC can you have a look as well?

**Comment by ArnaudIGRAC** [comment]
I tried a few wells and it looks good! Unless you notice something, this thread can be closed

**Comment by clau1313** [comment]
Hi @meomancer, is it possible to see in the dropdown menu only the parameters for which the well has data? For instance, this wells has T data:

![image](https://user-images.githubusercontent.com/36033176/214307634-ebbe1ad5-1806-4889-b7ab-d4a319a46205.png)

and doesn't have Ca data:

![image](https://user-images.githubusercontent.com/36033176/214307720-82762dfe-8486-4a74-97eb-23e291dd1c44.png)

So the dropdown menu should show only the parameters for which there is data: 

![image](https://user-images.githubusercontent.com/36033176/214307978-cfb6eedb-a8d0-4443-b245-9211ab254777.png)

can you please do that? thanks!

**Comment by meomancer** [comment]
hi @clau1313 
It is updated, could you check it on staging?

**Comment by clau1313** [comment]
hi @meomancer 
In general it seems that it is working but not in all wells, for example this one:

![image](https://user-images.githubusercontent.com/36033176/214573792-4213ab65-f5c9-4f6f-b0ca-6f030db2df62.png)

Or is this well empty? In that case it should't appear in the GGMN, right? 

Also, in some cases I see the parameter "groundwater anomaly" for which there is no data:

![image](https://user-images.githubusercontent.com/36033176/214574263-6549eec4-147e-4325-974a-2d10e2ddf343.png)

Another question, is it possible to display "groundwater quality" and "groundwater yield" in a different way than the actual parameters? because now it looks like you could click on them or as if they are extra parameters, but they are just subtitles. Perhaps they can appear in bold?

![image](https://user-images.githubusercontent.com/36033176/214574610-aadf1f20-6e74-4a21-8fd9-5486c1ff2266.png)

**Comment by meomancer** [comment]
Hi @clau1313 
Staging updated

For New Zealand 144/0101
Yes, it does not have any measurement.
Where did you check it?

It is show in well and monitoring data
![Selection_016](https://user-images.githubusercontent.com/4530905/214764067-7a943545-9c23-4a9e-9387-c72780ac07ac.png)

But it is already not showing on ggmn
![Selection_017](https://user-images.githubusercontent.com/4530905/214764101-40152c7f-d8a1-436d-8cd1-28495b7b70a7.png)

Also i fixed the norway well
![Selection_018](https://user-images.githubusercontent.com/4530905/214764109-1e0b8bb7-1d55-46af-94e7-4f5d365071ab.png)

And also, for the title group, i change it to bold
![Selection_019](https://user-images.githubusercontent.com/4530905/214764180-a2f728ed-9685-483d-b668-20d8e10d7033.png)
 and blue color. Please hard refresh

**Comment by clau1313** [comment]
Thanks @meomancer! All is good :)
