### ISSUE TITLE
Upload layer doesn't work

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#544]
I can't replace or upload this layer. I don't understand why. Can you please have a look?
[2021_Mastefile.zip](https://github.com/kartoza/IGRAC-GGIS/files/11146719/2021_Mastefile.zip)
![image](https://user-images.githubusercontent.com/64771599/229745134-54f8fc09-756f-4fbf-982a-088e6e558c6d.png)

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
I'm sorry, it is fixed, could you retry ?

**Comment by ArnaudIGRAC** [comment]
No, it doesn't work

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
Here is the error from my side now

![Selection_020](https://user-images.githubusercontent.com/4530905/230820119-9077f5ea-7ec2-4521-9e45-662697d254bc.png)

I think because of there are some invalid geometries.
![Selection_021](https://user-images.githubusercontent.com/4530905/230820304-ecdc6a94-f67c-4752-b9d8-209458014448.png)

Example:
![Selection_022](https://user-images.githubusercontent.com/4530905/230820316-94155cd7-53e2-4945-ad19-1fe75bb337ad.png)

I tried using my shapefile, it is working fine
