### ISSUE TITLE
map viewers modified since upgrade

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#553]
I noticed that some viewers have been modified since the upgrade to GeoNode 4. Take for example the GGMN viewer, which now appears with new visible layers (transboundary aquifers). Please restaure the map viewers as they were
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/7fac9a11-096e-4925-b46e-90f89c7d7d38)

**Comment by ArnaudIGRAC** [comment]
Also, some new folders have been created and layers have been added, see for instance 
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/d02bf088-f051-4a2c-8843-3eb4194fccfa)
or
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/63b9ade9-56af-4bbd-9b1b-a08699037739)

**Comment by dimasciput** [comment]
Hi @ArnaudIGRAC , I can answer regarding the new folder. With the lnewf GeoNode, you cannot add a layer to the map without a group. This is why a default group is created automatically.

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
The structure is coming from migrating to geonode 4.
I'm not sure how the best method to restore it, because although we restore the database, it will automatically migrating to this new structure on geonode 4.

I would say maybe we can clean it manually.
It is just duplicated some layers and put it on default folder.

I have fixed the GGMN map, but i'm not sure for other maps

**Comment by ArnaudIGRAC** [comment]
OK, I will do a bit of manual cleaning

**Comment by meomancer** [comment]
thank you @ArnaudIGRAC
