### ISSUE TITLE
manage permissions doesn't work

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#565]
I tried to change the permission of my geostory https://ggis.un-igrac.org/catalogue/#/geostory/2233
However many users are not in the list, see for example elie.gerges@un-igrac.org
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/4f225fb5-9423-4b66-877f-9f619d17dbc5)

Moreover, when trying to assign a group, some groups come with a "bin" icon next to them instead of a "cross"
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/9046ebf0-4d6f-41ef-8c15-8389f2423513)

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 

> I tried to change the permission of my geostory https://ggis.un-igrac.org/catalogue/#/geostory/2233
However many users are not in the list, see for example [elie.gerges@un-igrac.org](mailto:elie.gerges@un-igrac.org)

This is logic from geonode. elie is superuser, which is exluded from options, because regardless he has permission or not, he can see, edit, delete the geostory because he is superuser. As well as your user, admin user, etc.

> Moreover, when trying to assign a group, some groups come with a "bin" icon next to them instead of a "cross"

This is bug from geonode, i have fixed it on staging, could you try it for now?

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan! Yes, it works fine in staging
