### ISSUE TITLE
scroll maps horizontally

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#567]
Hi Admire, how do you determine whether a map can be scrolled horizontally across the -180/180 line? like on this figure for example
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/4963c68f-8649-42cd-999a-649cc693e151)

**Comment by ArnaudIGRAC** [comment]
Dear colleagues, could you please change the settings so that the maps can scroll horizontally instead of being bound at -180 and 180?

**Comment by ArnaudIGRAC** [comment]
Can anybody help us with that?

**Comment by NyakudyaA** [comment]
The default map settings are stored in a json configurations. We will need to adjust it to reflect this. @meomancer Can you check inside the geonode image what is defined with https://docs.mapstore.geosolutionsgroup.com/en/latest/developer-guide/maps-configuration/

**Comment by meomancer** [comment]
hi @NyakudyaA 
This config?
https://github.com/kartoza/geonode-mapstore-client/blob/4.0.9/geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
or
https://github.com/kartoza/geonode-mapstore-client/blob/4.0.9/geonode_mapstore_client/client/static/mapstore/configs/map.json

**Comment by NyakudyaA** [comment]
Let me take a look and I will let you know what you need to adjust

**Comment by NyakudyaA** [comment]
@meomancer Can we try to define the map extent in the map.json
```
"maxExtent": [
        -20037508.34, -20037508.34,
        20037508.34, 20037508.34
    ],
```
But we would need a way to find the layer with the largest coverage (extent) from the https://github.com/kartoza/geonode-mapstore-client/blob/4.0.9/geonode_mapstore_client/client/static/mapstore/configs/map.json#L32

See other examples here https://github.com/geosolutions-it/mapstore-playground/blob/master/new.json

**Comment by meomancer** [comment]
hi @NyakudyaA 
thank you, i will play with it

**Comment by ArnaudIGRAC** [comment]
Any update on that?

**Comment by meomancer** [comment]
hi @NyakudyaA 
I have checked using geonode mapstore that we use on igrac directly
and their map.json are similiar
![Selection_007](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/88642d5f-bf9f-487f-83ef-6b68bca47e7a)
![Selection_008](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/fb4b94b1-9f57-45ee-baad-1448cd973bd9)

But they behave differently
On igrac, it is wrap-x
![Selection_005](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/97884546-2685-43f7-8a8e-d13324233371)

on geonode mapstore, it is correct, although the geonode mapstore is the mapstore that we use on igrac
![Selection_006](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/6a158e0a-a121-4dff-b038-d373ec8c50ba)

So my suspicious is on igrac settings that i'm not sure where is it.
Maybe i will try to ask @dimasciput , maybe there is setting that i miss, otherwise, i need time to dive in to the code

I'm really sorry @ArnaudIGRAC 
I have already committed to other project, and this ticket needs more time for me to check it
I will ask @MarinaKartoza to help me create time for me for igrac

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Now it has duplicated map, but we can't setting it per map, so i just make it duplicated now.

And also, the ggis has just 1 map because of this request:
https://github.com/kartoza/IGRAC-GGIS/issues/556
