### ISSUE TITLE
Batch upload

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-GGIS#603]
Hi @meomancer, we would like to upload some data but it looks like the batch upload tool is stuck in the last time we tried to upload data:

![image](https://github.com/kartoza/IGRAC-GGIS/assets/36033176/10542404-3236-4287-be32-3dff97c5da41)

Can you please "reset" the tool so we can start uploading more data? Thanks!

**Comment by meomancer** [comment]
Hi @clau1313 
I already flag it as cancelled
It seems that the server was down and the importer stuck
Could you reupload?

**Comment by clau1313** [comment]
@Eliegergesgerges can you please follow up next week? :)

**Comment by Elie114** [comment]
Hi Irwan! 
Concerning this issue, I've encountered the same problem trying to upload this file (it stopped and you told me to upload it again).  
On the third attempt, the process is notably slow, especially when dealing with this particular file upload. What can be done to address and resolve this problem?

**Comment by meomancer** [comment]
Hi @clau1313 @Elie114 
The upload stuck is because the server is restarted but the app does not continue the process

Now the upload will be resumed when server is restarted
And also it has indicator of the status. If it is stopped, we can resume it manually
https://github.com/kartoza/IGRAC-GGIS/issues/610#issuecomment-1855452000

And also @Elie114 
I also fix the slowness of process

The speed is around 20 records per second
We have 1 milian records
