### ISSUE TITLE
Replace layer

### ISSUE THREAD

**Issue by SterckxArnaud** [kartoza/IGRAC-GGIS#605]
Hi Irwan, I need to update a layer in the GGIS. In GeoNode 3, I would simply replace the layer with the new one, but that functionality is no longer available. I could edit the layer in GeoNode, but I can only draw the features by hand, I can't assign the coordinates of the vertices. Another option would be to create a new layer and delete the old one, but then I would need to edit all the maps where the layer is contained, and the url address of the layer will not be the same (former url will be broken). 

Could you please assist? Is there a chance that you can replace the layer in the back end?

The layer that I would liek to replace is https://ggis.un-igrac.org/catalogue/#/dataset/1810
Here is the updated layer: [20231130_GGIS_MAR.zip](https://github.com/kartoza/IGRAC-GGIS/files/13510934/20231130_GGIS_MAR.zip)

**Comment by meomancer** [comment]
Hi @SterckxArnaud 
I'm not sure, i have asked @NyakudyaA to follow up this question

**Comment by NyakudyaA** [comment]
@SterckxArnaud Unfortunately it seems this option has been removed in GeoNode 4. The most likely method to use is

* Navigate to QGIS and select the plugin. Install the QGIS GeoNode plugin.
* Navigate to the Datasource Manager and choose QGIS GeoNode
* Add a new connection and add your authentication credentials
![image](https://github.com/kartoza/IGRAC-GGIS/assets/2510900/8ddbcb32-ee4a-43eb-bde0-54a7282fdad4)

* Search for your resources
* Add the layer as WFS
![image](https://github.com/kartoza/IGRAC-GGIS/assets/2510900/092d003f-f893-4840-a15f-e7be4690fb5f)

* Once the layer is loaded in QGIS, toggle edit the layer.
* Load the new layer with new features
* Open the new features and select them, choose copy all rows
* Open the WFS layer whilst in edit mode, select all features and delete them.
* Paste the new features and save the WFS.

Alternatively, we can just use the backend to upload the layer and replace it in the DB. 
Please let me know if you want to try the first method otherwise I can do option 2

**Comment by SterckxArnaud** [comment]
Thank you Admire. I did try this but it doesn't work. I am not authorized to save the edits that I make to the layer. I don't see that the API client capabilities include something to actually modify vector layers. How shall I proceed?

![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/05f4ebec-915e-437a-9c5e-939f0fd7f0ff)

**Comment by NyakudyaA** [comment]
@SterckxArnaud Can you try again? I have  updated the WFS setting to be transactional

**Comment by SterckxArnaud** [comment]
Yes please

**Comment by NyakudyaA** [comment]
This is complete
