### ISSUE TITLE
Stop an upload

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#631]
Hi guys,

1) Please can you stop an upload for an excel file that we are trying to upload there are important edits to be done. (picture attached)

2) Also, it is very important if we can speed up the upload of the wells as we are slightly late for a deadline. Please let me know about these tasks.

Regards,
Elie

**Comment by meomancer** [comment]
Hi @Eliegergesgerges 
I have stopped the upload

Now we can stop the upload
![Selection_009](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/0481b65f-2b4b-4503-9d77-134a35c4d7f8)

```
2. Also, it is very important if we can speed up the upload of the wells as we are slightly late for a deadline. Please let me know about these tasks.
```
Unfortunately, we can't speed up because there are process for checking data on upload.
I need to do RnD and it will change a lot of logic in the process
So it will take time to do that

I have create ticket for that:
[Improve speed of uploader](https://github.com/kartoza/IGRAC-GGIS/issues/633)

I will work on it friday next week, and after that we need to test it on staging first before release it

But today, i will work on [Able to multi batch upload in one time](https://github.com/kartoza/IGRAC-GGIS/issues/634), hopefully i can release it today

**Comment by Elie114** [comment]
We cam close this one
