### ISSUE TITLE
GGMN Download 

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#665]
There appears to be a discrepancy on the GGMN platform between the number of wells visible on the interface and the actual data downloaded. For instance, when checking Sweden on the platform, I can see 61 wells, but upon downloading the data, I received 411 Excel files in the monitoring section. It's crucial to ensure that the downloaded data aligns with what is visible on the GGMN platform.

Additionally, for the United States, the platform indicates 3263 wells, but the Excel file containing well information, labeled 'wells,' contains data for 105,000 wells. This discrepancy raises concerns, as the number of wells on the GGMN should match the count in the downloaded files. It's essential to investigate and resolve these inconsistencies to maintain data accuracy and reliability on the platform.

Priority: Medium

**Comment by meomancer** [comment]
hi @Eliegergesgerges and @SterckxArnaud 
Could you check this?

Now the ggmn is using ggmn data that we setup on Layer

To make the download data sync with the layer, we need to change "is ggmn layer" on the layer that we use on map
It is on django admin : https://ggis.un-igrac.org/en-us/admin/igrac/groundwaterlayer/
![Selection_122](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/47f06282-af75-4a95-a7f8-f48c8ab95958)
![Selection_121](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/54a9d362-ea95-4e9e-9ea8-5a87cbf0d220)
   
So if we change the ggmn map layer to a new layer, we need to flag it as "is ggmn layer" (and remove it from old one).
Because by default, if we don't flag any layer, the download data will use all organisations.
Please check it

Also for the United States it will not be the same between map and also the download file. 
Because the download file is a cache, meanwhile the harvester is still running and the map is updated live.
So when the harvester finish, the download file and map will be same (it depends on below point)
